version: "{build}"

os: Visual Studio 2017

install:
  - git submodule update --init --recursive
  - ps: .\Build\Setup-Build-Environment.ps1
  - ps: .\Build\Download-Standalone-Core.ps1

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(pactnet_assembly_version)"
  assembly_file_version: "$(pactnet_assembly_version)"
  assembly_informational_version: "$(pactnet_version)"

deploy:
  - provider: NuGet
    skip_symbols: true
    api_key:
      secure: iow2hdf0OK68MNKVYq7/1JMVTRz6xbW+yC7PwtEsGzfKCT56KUYLANRe/IxusAeR
    on:
      appveyor_repo_tag: true

artifacts:
  - path: '**\Build\PactNet*.nupkg'
  - path: '**\Build\coverage\*'

configuration: Release

build:
  project: PactNet.sln
  verbosity: minimal

before_build:
  - nuget restore

after_test:
  - ps: .\Build\Tests-Coverage.ps1 -GenerateSummaryReport
  - ps: .\Build\Publish-Release.ps1 -ReleaseVersionNumber "$env:PACTNET_VERSION"
  - ps: .\Build\Publish-StandaloneCore-Releases.ps1 -ReleaseVersionNumber "$env:PACTNET_VERSION"
